modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="ae2clienttweaks"
version="${file.jarVersion}"
displayName="AE2 Client Tweaks"
authors="Texbio"
displayURL="https://www.curseforge.com/minecraft/mc-mods/ae2-client-tweaks"
logoFile="ae2clienttweaks_logo.png"
description='''
Client-side tweaks for Applied Energistics 2.
- Shift-click patterns from inventory into Molecular Assembler slots in the Pattern Access Terminal
- Block shift-clicking patterns into the ME network when terminal view is set to Craftable
'''

[[dependencies.ae2clienttweaks]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="CLIENT"

[[dependencies.ae2clienttweaks]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="CLIENT"

[[dependencies.ae2clienttweaks]]
modId="ae2"
mandatory=true
versionRange="[15.0.0,)"
ordering="AFTER"
side="CLIENT"
